name: Hello World Workflow
run-name: ${{ github.actor }} is running the Hello World action ðŸš€
on: [push]

jobs:
  say-hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the world
        run: echo "ðŸŽ‰ Hello, world! This is my first GitHub Action."
      - name: Display current repository
        run: echo "ðŸ”Ž This workflow is running in the ${{ github.repository }} repository."
